CREATE TABLE ADM_NOTI (
    EMAIL_DESTINATARIO VARCHAR2(255),
    ASUNTO VARCHAR2(255),
    CCUERPO VARCHAR2(255),
    FIRMA VARCHAR2(255),
    CENTE VARCHAR2(255),
    ERROR NUMBER,
    NUM_NOTIFICACION NUMBER,
    CANT_ENVIOS NUMBER,
    CBA_FEC_ULT_ENVIO DATE,
    CONSTRAINT PK_ADM_NOTI PRIMARY KEY (NUM_NOTIFICACION)
);

CREATE SEQUENCE secuencia_notificaciones
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOMINVALUE
    CACHE 2;

CREATE OR REPLACE TRIGGER tr_generar_secuencia
BEFORE INSERT ON ADM_NOTI
FOR EACH ROW
BEGIN
    SELECT secuencia_notificaciones.NEXTVAL INTO :NEW.NUM_NOTIFICACION FROM DUAL;
END;
/